### ISSUE TITLE
Ditto should not be able to earn Gen IV Contest Ribbons

### ISSUE THREAD

**Issue by Azekthi** [Azekthi/Ribbons.Guide#73]
[From Rusher on Discord:](https://discord.com/channels/1080506053101375579/1156105984176037928/1166586648323162213)

> Ditto cant get the contest ribbon in gen 4 legit but the sie says yes

[From autumn on Discord:](https://discord.com/channels/1080506053101375579/1156105984176037928/1166667937827004436)

> i believe it can with the use of glitches to give yourself more than 1 move, and transporter/home wont care, but i agree it shouldnt be listed on the site (at least not without proper notice)

From a cursory web search, I found one person mention a "Rage glitch" is required, and I found someone else mention that it's perfectly legal, so I need more information to make an informed decision.

**Comment by SadisticMystic** [comment]
Super Contests have an acting phase that lasts for 4 turns. Unlike in Hoenn's contests, where you can repeat moves but get a heart penalty for doing so, here you are physically locked out of choosing the same move you picked last turn. The exception is moves that have a specific effect (mostly multi-hit moves like Double Kick) allowing you to use them twice in a row, but no more, thus the four turns would have to be something like A-A-B-A and you still need a second move for at least one of the turns.

As such, the contest receptionist will refuse to let you enter a contest with a Pokemon that currently has only one move, and if the species only ever gets a single move no matter what (Unown and Ditto), that means it can't legally participate in the region's contests. There have been code execution exploits found for DP, which means that instead of having to use something like PKHeX to edit a second move onto those Pokemon and allow them to enter the contests, it can be done using purely in-game means; however, these means can't be considered "legal" since they could just as well be used to directly award blatantly out-of-place stuff like all the event ribbons at once.

For Ditto in particular, if it transforms into a Pokemon that knows Rage, it can make use of a separate glitch to obtain other moves permanently, which would allow it to earn the second half of the contest ribbons that way. This is somewhat more constrained than the full-blown ACE techniques, but still not considered legal, as its other consequences include stuff like Sheer Cold Machamp.
